### ISSUE TITLE
Add Python 3.7 to Travis

### ISSUE THREAD

**Issue by GiacomoLaw** [GiacomoLaw/leaguestatistics#28]
```
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
```

More info: https://github.com/travis-ci/travis-ci/issues/9815
